// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg41xbjsLSRPOOFferKz7aOCdUDdLCxuk',
    appId: '1:136711842069:web:02bd9f7c4a0c2a4b53611c',
    messagingSenderId: '136711842069',
    projectId: 'testapp-e1dec',
    authDomain: 'testapp-e1dec.firebaseapp.com',
    storageBucket: 'testapp-e1dec.appspot.com',
    measurementId: 'G-5FGENHM802',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNkKTm7VSHm8Hb8atCbylFwW972TIpSO8',
    appId: '1:136711842069:android:17ff077b558c39eb53611c',
    messagingSenderId: '136711842069',
    projectId: 'testapp-e1dec',
    storageBucket: 'testapp-e1dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6PNtFADZUQgwojhBNu8NCesG74goDS8',
    appId: '1:136711842069:ios:51674b8642bf86df53611c',
    messagingSenderId: '136711842069',
    projectId: 'testapp-e1dec',
    storageBucket: 'testapp-e1dec.appspot.com',
    iosBundleId: 'com.example.docTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6PNtFADZUQgwojhBNu8NCesG74goDS8',
    appId: '1:136711842069:ios:51674b8642bf86df53611c',
    messagingSenderId: '136711842069',
    projectId: 'testapp-e1dec',
    storageBucket: 'testapp-e1dec.appspot.com',
    iosBundleId: 'com.example.docTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVcyKsEhtwwL2W6-u47tk66mGFKIoA7fY',
    appId: '1:136711842069:web:331937a20fcefec653611c',
    messagingSenderId: '136711842069',
    projectId: 'testapp-e1dec',
    authDomain: 'testapp-e1dec.firebaseapp.com',
    storageBucket: 'testapp-e1dec.appspot.com',
    measurementId: 'G-GNRV8WXHQS',
  );
}
